services:
    admin.card:
        class: Letscode\Bundle\MagicBundle\Admin\CardAdmin
        arguments: [~, Letscode\Bundle\MagicBundle\Entity\Card, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Card }
    admin.manacost:
        class: Letscode\Bundle\MagicBundle\Admin\ManaCostAdmin
        arguments: [~, Letscode\Bundle\MagicBundle\Entity\ManaCost, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: ManaCost }
    admin.color:
        class: Letscode\Bundle\MagicBundle\Admin\ColorAdmin
        arguments: [~, Letscode\Bundle\MagicBundle\Entity\Color, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Color }
    admin.edition:
        class: Letscode\Bundle\MagicBundle\Admin\EditionAdmin
        arguments: [~, Letscode\Bundle\MagicBundle\Entity\Edition, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Edition }