services:
    admin.card:
        class: Letscode\Bundle\MagicBundle\Admin\CardAdmin
        arguments: [~, Letscode\Bundle\MagicBundle\Entity\Card, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Card }
    admin.manacost:
        class: Letscode\Bundle\MagicBundle\Admin\ManaCostAdmin
        arguments: [~, Letscode\Bundle\MagicBundle\Entity\ManaCost, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, label: ManaCost }
    admin.color:
        class: Letscode\Bundle\MagicBundle\Admin\ColorAdmin
        arguments: [~, Letscode\Bundle\MagicBundle\Entity\Color, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Color }
    admin.edition:
        class: Letscode\Bundle\MagicBundle\Admin\EditionAdmin
        arguments: [~, Letscode\Bundle\MagicBundle\Entity\Edition, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Edition }
    admin.cardtype:
        class: Letscode\Bundle\MagicBundle\Admin\CardTypeAdmin
        arguments: [~, Letscode\Bundle\MagicBundle\Entity\CardType, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: CardType }
    admin.effect:
        class: Letscode\Bundle\MagicBundle\Admin\EffectAdmin
        arguments: [~, Letscode\Bundle\MagicBundle\Entity\Effect, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Effect }
    admin.attribute:
        class: Letscode\Bundle\MagicBundle\Admin\AttributeAdmin
        arguments: [~, Letscode\Bundle\MagicBundle\Entity\Attribute, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Attribute }