letscode_magic:
    resource: "@LetscodeMagicBundle/Resources/config/routing.yml"
    prefix:   /

# Sonata Configuration
admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin