Letscode\Bundle\MagicBundle\Entity\CardType:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
    lifecycleCallbacks: {  }
