Letscode\Bundle\MagicBundle\Entity\Card:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
        convertedManaCost:
            type: integer
    manyToMany:
        colors:
            targetEntity: Color
            joinTable:
                name: cards_colors
                joinColumns:
                    cardId:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColums:
                    colorId:
                        referencedColumnName: id
        editions:
            targetEntity: Edition
            joinTable:
                name: cards_editions
                joinColumns:
                    cardId:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    editionId:
                        referencedColumnName: id
        manaCosts:
            targetEntity: ManaCost
            joinTable:
                name: cards_manacosts
                joinColumns:
                    cardId:
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    manaCostId:
                        referencedColumnName: id
        cardTypes:
            targetEntity: CardType
            joinTable:
                name: cards_cardtypes
                joinColumns:
                    cardId:
                        referenceColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    cartTypeId:
                        referenceColumnName: id
    lifecycleCallbacks: {  }
