Letscode\Bundle\MagicBundle\Entity\Color:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '255'
    oneToMany:
        manaCosts:
            targetEntity: ManaCost
            mappedBy: color
            cascade: ["persist"]
    lifecycleCallbacks: {  }
